language: node_js
node_js:
  - "8"
  - "7"
  - "6"
install: npm install

jobs:
  include:
    - stage: test
      script: bash ./scripts/test.sh

cache:
  directories:
    - node_modules

notifications:
  email: false
